spring:
  application:
    name: navermap

constants:
  naver-map:
      geocode-url: https://maps.apigw.ntruss.com/map-geocode/v2/geocode
      direction-url: https://maps.apigw.ntruss.com/map-direction/v1/driving
      app-key: ${NAVER_MAP_APP_KEY}
      secret-key: ${NAVER_MAP_SECRET_KEY}